# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               AskBeautifulQuestions
tagline:             'Ethnography for Everyone'
description:         'Ethnography for Everyone'
url:                 askbeautifulquestions.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Beth M. Duckles
  url:               beth.duckles.com
  email:             beth@duckles.com

# Custom vars
version:             1.0.0
